/*
 * QUANTCONNECT.COM - Democratizing Finance, Empowering Individuals.
 * Lean Algorithmic Trading Engine v2.0. Copyright 2014 QuantConnect Corporation.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.quantconnect.lean;

import com.google.common.collect.ImmutableList;
import com.google.common.collect.ImmutableMap;

/**
 * Provides commonly used currency pairs and symbols
 */
public class Currencies {
    
    private Currencies() { }
    
    /**
     * Gets the listing of currently supported currency pairs.
     * 
     * This listing should be in sync with the data available at: https://www.quantconnect.com/data/FOREX#2.1.1
     * It must include all currency pairs needed to resolve quote currencies in <see cref="Cash.EnsureCurrencyDataFeed"/>
     */
    public static final ImmutableList<String> CURRENCY_PAIRS = ImmutableList.<String>builder()
        // these are listed at the top to ensure they get selected first when resolving
        // currency data feeds. the case that showcases the issue is we would select jpyusd
        // instead of usdjpy, even though jpyusd is much less common
            .add( "AUDJPY" )
            .add( "AUDUSD" )
            .add( "EURCHF" )
            .add( "EURGBP" )
            .add( "EURJPY" )
            .add( "EURUSD" )
            .add( "GBPAUD" )
            .add( "GBPJPY" )
            .add( "GBPUSD" )
            .add( "NZDUSD" )
            .add( "USDCAD" )
            .add( "USDCHF" )
            .add( "USDJPY" )
            .add( "USDHKD" )
            .add( "USDSGD" )
            .add( "XAGUSD" )
    
    
            .add( "AUDCAD" )
            .add( "AUDCHF" )
            .add( "AUDCNY" )
            .add( "AUDCZK" )
            .add( "AUDDKK" )
            .add( "AUDHKD" )
            .add( "AUDHUF" )
            .add( "AUDINR" )
            .add( "AUDMXN" )
            .add( "AUDNOK" )
            .add( "AUDNZD" )
            .add( "AUDPLN" )
            .add( "AUDSAR" )
            .add( "AUDSEK" )
            .add( "AUDSGD" )
            .add( "AUDTHB" )
            .add( "AUDTRY" )
            .add( "AUDTWD" )
            .add( "AUDZAR" )
            .add( "CADAUD" )
            .add( "CADCHF" )
            .add( "CADCNY" )
            .add( "CADCZK" )
            .add( "CADDKK" )
            .add( "CADHKD" )
            .add( "CADHUF" )
            .add( "CADINR" )
            .add( "CADJPY" )
            .add( "CADMXN" )
            .add( "CADNOK" )
            .add( "CADNZD" )
            .add( "CADPLN" )
            .add( "CADSAR" )
            .add( "CADSEK" )
            .add( "CADSGD" )
            .add( "CADTHB" )
            .add( "CADTRY" )
            .add( "CADTWD" )
            .add( "CADZAR" )
            .add( "CHFAUD" )
            .add( "CHFCAD" )
            .add( "CHFCNY" )
            .add( "CHFCZK" )
            .add( "CHFDKK" )
            .add( "CHFHKD" )
            .add( "CHFHUF" )
            .add( "CHFINR" )
            .add( "CHFJPY" )
            .add( "CHFMXN" )
            .add( "CHFNOK" )
            .add( "CHFNZD" )
            .add( "CHFPLN" )
            .add( "CHFSAR" )
            .add( "CHFSEK" )
            .add( "CHFSGD" )
            .add( "CHFTHB" )
            .add( "CHFTRY" )
            .add( "CHFTWD" )
            .add( "CHFUSD" )
            .add( "CHFZAR" )
            .add( "CNYJPY" )
            .add( "CZKJPY" )
            .add( "DKKJPY" )
            .add( "EURAUD" )
            .add( "EURCAD" )
            .add( "EURCNY" )
            .add( "EURCZK" )
            .add( "EURDKK" )
            .add( "EURHKD" )
            .add( "EURHUF" )
            .add( "EURINR" )
            .add( "EURMXN" )
            .add( "EURNOK" )
            .add( "EURNZD" )
            .add( "EURPLN" )
            .add( "EURSAR" )
            .add( "EURSEK" )
            .add( "EURSGD" )
            .add( "EURTHB" )
            .add( "EURTRY" )
            .add( "EURTWD" )
            .add( "EURZAR" )
            .add( "GBPCAD" )
            .add( "GBPCHF" )
            .add( "GBPCNY" )
            .add( "GBPCZK" )
            .add( "GBPDKK" )
            .add( "GBPHKD" )
            .add( "GBPHUF" )
            .add( "GBPINR" )
            .add( "GBPMXN" )
            .add( "GBPNOK" )
            .add( "GBPNZD" )
            .add( "GBPPLN" )
            .add( "GBPSAR" )
            .add( "GBPSEK" )
            .add( "GBPSGD" )
            .add( "GBPTHB" )
            .add( "GBPTRY" )
            .add( "GBPTWD" )
            .add( "GBPZAR" )
            .add( "HKDCNY" )
            .add( "HKDCZK" )
            .add( "HKDDKK" )
            .add( "HKDHUF" )
            .add( "HKDINR" )
            .add( "HKDJPY" )
            .add( "HKDMXN" )
            .add( "HKDNOK" )
            .add( "HKDPLN" )
            .add( "HKDSAR" )
            .add( "HKDSEK" )
            .add( "HKDSGD" )
            .add( "HKDTHB" )
            .add( "HKDTRY" )
            .add( "HKDTWD" )
            .add( "HKDZAR" )
            .add( "INRJPY" )
            .add( "JPYHUF" )
            .add( "JPYUSD" )
            .add( "MXNJPY" )
            .add( "NOKJPY" )
            .add( "NZDCAD" )
            .add( "NZDCHF" )
            .add( "NZDHKD" )
            .add( "NZDJPY" )
            .add( "NZDSGD" )
            .add( "PLNJPY" )
            .add( "SARJPY" )
            .add( "SEKJPY" )
            .add( "SGDCHF" )
            .add( "SGDCNY" )
            .add( "SGDCZK" )
            .add( "SGDDKK" )
            .add( "SGDHKD" )
            .add( "SGDHUF" )
            .add( "SGDINR" )
            .add( "SGDJPY" )
            .add( "SGDMXN" )
            .add( "SGDNOK" )
            .add( "SGDPLN" )
            .add( "SGDSAR" )
            .add( "SGDSEK" )
            .add( "SGDTHB" )
            .add( "SGDTRY" )
            .add( "SGDTWD" )
            .add( "SGDZAR" )
            .add( "THBJPY" )
            .add( "TRYJPY" )
            .add( "TWDJPY" )
            .add( "USDAUD" )
            .add( "USDCNY" )
            .add( "USDCZK" )
            .add( "USDDKK" )
            .add( "USDEUR" )
            .add( "USDGBP" )
            .add( "USDHUF" )
            .add( "USDINR" )
            .add( "USDMXN" )
            .add( "USDNOK" )
            .add( "USDPLN" )
            .add( "USDSAR" )
            .add( "USDSEK" )
            .add( "USDTHB" )
            .add( "USDTRY" )
            .add( "USDTWD" )
            .add( "USDZAR" )
            .add( "ZARJPY" )
            .build();

    /**
     * A mapping of currency codes to their display symbols
     * 
     * Now used by Forex and CFD, should probably be moved out into its own class
     */
    public static final ImmutableMap<String,String> CURRENCY_SYMBOLS = ImmutableMap.<String,String>builder()
            .put( "USD", "$"  )
            .put( "GBP", "₤" )
            .put( "JPY", "¥" )
            .put( "EUR", "€" )
            .put( "NZD", "$" )
            .put( "AUD", "$" )
            .put( "CAD", "$" )
            .put( "CHF", "Fr" )
            .put( "HKD", "$" )
            .put( "SGD", "$" )
            .put( "XAG", "Ag" )
            .put( "CNY", "¥" )
            .put( "CZK", "Kč" )
            .put( "DKK", "kr" )
            .put( "HUF", "Ft" )
            .put( "INR", "₹" )
            .put( "MXN", "$" )
            .put( "NOK", "kr" )
            .put( "PLN", "zł" )
            .put( "SAR", "﷼" )
            .put( "SEK", "kr" )
            .put( "THB", "฿" )
            .put( "TRY", "₺" )
            .put( "TWD", "NT$" )
            .put( "ZAR", "R" )
            .build();
}
